language:
  - cpp

os:
  - linux
  - osx

script:
  - CXXFLAGS="-coverage"
  - LDFLAGS="-coverage"
  - mkdir -p build
  - cd build
  - cmake ..
  - cmake --build . --config Debug
  - ./ZmeyaTest

after_success:
  - ls
