language:
  - cpp

os:
  - linux
  - osx

addons:
  apt:
    packages: lcov

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - cmake --build . --config Release
  - ./ZmeyaTest

after_success:
  - ls
