version: "{branch}-ci-{build}"
image: Visual Studio 2017

build: msvc
platform: x86
configuration: Debug

install:
- choco install opencppcoverage codecov
- set PATH=C:\Program Files\OpenCppCoverage;%PATH%

build_script:
- git submodule update --init --recursive
- mkdir build
- cd build
- cmake ..
- cd ..
- cmake --build .\build\ --config Debug
- OpenCppCoverage.exe --export_type=cobertura:cobertura.xml --sources Zmeya*.* --excluded_sources *googletest* --modules *.exe -- .\build\Debug\ZmeyaTest.exe
- codecov -f cobertura.xml --root %APPVEYOR_BUILD_FOLDER% -t 11f29925-c727-4836-945c-a210c2756e2f
